name: 小川微信机器人
version: 0.2.2
menu:
  regex: ^([\u4e00-\u9fa5a-zA-Z0-9]+)[\s+:：_-]*(.*)$
  domain: # overridable
    contacts:
      - 南川
    groups:
      - CS魔法社V3
      - 中学生编程入门
  subscribes:
    - name: CALL_MENU
      name_zh: 服务列表
      keys:
        - 川川
        - 小川川
        - 小川小川
        - 服务列表
      output: 可用服务列表

    - name: CALL_HELP
      name_zh: 请求帮助
      keys:
        - 请求帮助
        - help
      input: 服务的中文/拼音/序号
      output: 服务的解释

    - name: GET_XGYQ_STATUS
      name_zh: 查疫情状态
      keys:
        - 查疫情
        - 查疫情状态
      input: 省份/城市/省份+城市
      output: 该省/市累计与当日的确诊、死亡、治愈数据
      todo: 支持国家级别的查询

    - name: GET_XGYQ_TREND
      name_zh: 查疫情趋势
      keys:
        - 查疫情趋势
      input: 省份/城市/省份+城市
      output: 该省/市最近确诊、死亡、治愈数据的趋势图
      todo: 支持国家级别的查询

    - name: GET_QSBK_TEXT
      name_zh: 讲个笑话
      keys:
        - 糗事百科
        - 糗事百科纯文
        - 讲个笑话
      output: 随机一条糗事百科纯文本内容
      todo:
        - 支持分类
        - 基于iOS获得更多素材
          
    - name: GEN_DALLE_IMAGES
      name_zh: AI画图
      desc: 基于DALLE的AI画图
      keys:
        - AI画图
        - AI作画
      input: 待输入的英文
      output: 随机图片
      todo: 全部九张图片