menu:
  regex: ^(\S+)\s*(.*)$
  domain: # 可以被覆盖
    contacts:
      - 南川
    groups:
      - CS魔法社V3
  subscribes:
    - name: CALL_MENU
      keys:
        - 川川
        - 小川川
        - 小川小川
      output:
        可用服务列表
    - name: CHECK_XGYQ
      keys:
        - 小川查疫情
        - 查疫情
      input:
        - 省份
        - 城市
        - 省份+城市
      output:
        该省/市累计与当日的确诊、死亡、治愈数据
      todo:
        支持国家级别的查询
